### ISSUE TITLE
[Feature Request] Add C++ Example

### ISSUE THREAD

**Issue by JevanUG** [aisstream/issues#14]
A c++ version of the example would be highly useful.

**Comment by aisstream** [comment]
We will add that to the list. One issue is the fragmentation of the C++ ecosystem makes it difficult to decide on which web-socket library and package manager to use for the example. 

Is there a particular library you would like to see the example written with ? For example the [Beast](https://github.com/boostorg/beast) web-socket library ?

**Comment by OgreTransporter** [comment]
I have added examples in C# (#61), C (#62) and C++ (#63).

For the examples with the API generator, I need a little longer because the generated files have to be corrected.

**Comment by JevanUG** [comment]
Hello,
I am very glad to see more examples, thank you!

I will keep you updated on the project I have in mind for this.

Kind Regards,

Jevan Dean

Founder & Lead Developer

Unmatched Games
***@***.***
www.unmatchedgames.com
[image: facebook] <https://www.facebook.com/UnmatchedGames>
[image: linkedin] <https://www.linkedin.com/in/jevan-dean-58669b14b/>

**Comment by aisstream** [comment]
A C++ example has been added.
