### ISSUE TITLE
[Feature Request][Completed] Is it possible to create a subscription to an array of MMSI?

### ISSUE THREAD

**Issue by dekarl** [aisstream/issues#15]
I'm experimenting with realtime transit data and thought about using AIS data for ferry location in Hamburg. As there are many other ships in Hamburg that I don't care about I'd prefer to filter server side.

Is it possible to create a subscription to an array of 26 MMSI? Basically these ships https://hadag.de/de/unsere-flotte/

The plan is to adapt https://github.com/HSLdevcom/suomenlinna-ferry-hfp to your feed for input and GTFS-RT for output and see what happens.

The official solution for integrating live ferry into the transit planning is a big project https://hadag.de/de/its/ such a simple hack would in principle work world wide which appeals to me.

**Comment by aisstream** [comment]
Currently it is not possible to filter on MMSI. We can look to support this in the future but the anticipated timeline would be mid summer at the earliest. 

If you were looking to adapt https://github.com/HSLdevcom/suomenlinna-ferry-hfp the fastest solution would be to implement some filtering of your own in your fork. If your restrict you bounding box to the Hamburg area I believe the amount of data you receive should be fairly small and thus I do not anticipate any performance issues unless you are extremely resource constrained.

**Comment by aisstream** [comment]
Hello we have added subscription filters on MMSI and message type. Please see our documentation page for details on the update!

**Comment by aisstream** [comment]
.
