### ISSUE TITLE
Is there currently an outage?

### ISSUE THREAD

**Issue by samuel-pratt** [aisstream/issues#18]
I'm hitting consistent EOF errors when trying to connect to the websocket. 

Previously it was running with no issue for the last month or two so I don't think it's an issue with my implementation, but it could be an issue there as well. The connection logic in Go is below:

```
        url := "wss://stream.aisstream.io/v0/stream"
	ws, _, err := websocket.DefaultDialer.Dial(url, nil)
	if err != nil {
		log.Error(err)
		return
	}
	defer ws.Close()

	subMsg := aisstream.SubscriptionMessage{
		APIKey:        os.Getenv("AIS_API_KEY"),
		BoundingBoxes: [][][]float64{{{59.0, -148.0}, {45.0, -117.0}}},
	}
```

**Comment by aisstream** [comment]
See https://github.com/aisstream/issues/issues/19

Yes, apologies we are experiencing an outage.

**Comment by samuel-pratt** [comment]
No worries, just wanted to confirm.

Love the project and have it used in a few apps, if you ever need a contributor I'd be happy to help.
