### ISSUE TITLE
Current Outage Starting May 13 05:00AM UTC

### ISSUE THREAD

**Issue by aisstream** [aisstream/issues#19]
We are experiencing an outage do to loss of connectivity between our services.

**Comment by aisstream** [comment]
We are working to restore connectivity to our service. However we are also experiencing issues connecting to an dependency which is out of our control. 

Due to this issue with a dependency the ETA of the is +24 hours.

**Comment by aisstream** [comment]
We are still under going an issue with a critical dependency. 

ETA of fix is still 24 hours+

**Comment by Mutturaj-BEL** [comment]
is there outage till today ???

**Comment by aisstream** [comment]
The issue with a dependency is resolved. We will be slowly restoring service throughout the day.

**Comment by aisstream** [comment]
We have began recovery. Clients should begin to receive data now.

**Comment by aisstream** [comment]
We have been recovered for 12+ hours.

**Comment by Mutturaj-BEL** [comment]
Thank u very much for your kind support.. 
We are able to receive data..
