### ISSUE TITLE
AIS service outage - Bad deployment due to service misconfiguration

### ISSUE THREAD

**Issue by zawaungmsi** [aisstream/issues#24]
Just around 12 PM June 1 2023 Pacific time, AIS streaming stop sending messages

**Comment by MichalSzulzyk** [comment]
I confirm, no signal at all :-(

**Comment by zawaungmsi** [comment]
web socket can open, but no data received

**Comment by EiniusHeinius** [comment]
:cry:

**Comment by aisstream** [comment]
Apologies we had a bad deployment where a critical service was scheduled on a node without access to the main websocket service due to a bug in the configuration. We have fixed this bug so it will not happen again.

You should begin seeing service now.

**Comment by zawaungmsi** [comment]
Thank you team! we are getting the AIS data.

**Comment by aisstream** [comment]
Closing as issue has been identified and we are recovered.
