### ISSUE TITLE
[Contribution] Feeding my NMEA stream into your network

### ISSUE THREAD

**Issue by rhiniodontypus** [aisstream/issues#34]
Hello, 

is there a possibility to support you by feeding my personal NMEA stream into your network? I have a high range receiving station for riverboats. It would be a great pleasure!

**Comment by aisstream** [comment]
Hello, @rhiniodontypus. Thank you for the offer but we currently are not set up to easily allow this to take place. We are in the future looking to enable this behaviour but currently do not support it.
