### ISSUE TITLE
[Bug][Fix Deployed] MSSI always value '0'

### ISSUE THREAD

**Issue by andergoros** [aisstream/issues#36]
Good morning:

My program has been working correctly (javascript/websockets) but now I am receiving always '0' at metadata/MMSI and 0 at a new field named MMSI_String.

Thank you

**Comment by jay-tux** [comment]
Happens here as well - with both the Python example(s) and our own C# backend

**Comment by jay-tux** [comment]
Probably related - some vessels have an empty name

**Comment by fgorina** [comment]
Happens the same. Also in headers has appeared a field MMSI_String with also integer value 0

**Comment by EiniusHeinius** [comment]
For me the same .... MetaData.MMSI is just 0

**Comment by aisstream** [comment]
This looks like a bug on our end. When was this first observed ? That will help us correlate it to a deployment.

**Comment by EiniusHeinius** [comment]
For me between 
July 25th 5:37 AM and
July 25th 5:57 AM

Should be GMT

**Comment by aisstream** [comment]
We have identified the issue. Two of our services had incompatible versions running causing MMSI to not not be correctly parsed when sent between the services. The issue should be mitigated but we will leave this issue open for now, until we observe the fix for the next few hours.

**Comment by jliebrand** [comment]
Out of interest, how does the MMSI relate to the UserID which appears to be the same thing? Is it always the same thing?

**Comment by aisstream** [comment]
@jliebrand Yes they are always equal. That is due to a weird naming decision that we cannot undue to ensure we do not break anyones clients.
