### ISSUE TITLE
Location Data Missing?

### ISSUE THREAD

**Issue by jlgabbar** [aisstream/issues#5]
Do you have AIS data near Port Klang, MY? I can successfully get data around Singapore but not around Port Klang. If it's not already included, are there any plans/roadmap on which to include. 

I'm using these coordinates for my bounding box 

`BoundingBoxes: [[[2.089417, 100.684923], [3.450099, 101.800035]]]`

**Comment by aisstream** [comment]
Unfortunately we do not have coverage for Port Klang and will very likely not have coverage in the near future. A map which contains our rough coverage is available here https://aisstream.io/coverage. 

Apologies for the inconvenience
