### ISSUE TITLE
[Outage][Resolved] Websocket SSL Expiration

### ISSUE THREAD

**Issue by Jason-M-Spark** [aisstream/issues#50]
Trying to listen to the stream and I'm getting a `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired` error. Did a quick check on an SSL verifier and it seems like the certificate needs renewal.

**Comment by aisstream** [comment]
Apologies, though we have configured automatic cert updates, our load balancer did pick up the renewed cert automatically leading to the error.

**Comment by aisstream** [comment]
We have tested it and the service should be running as normal now.
