### ISSUE TITLE
Websocket SSL Expiration

### ISSUE THREAD

**Issue by MarcJulia** [aisstream/issues#71]
Trying to listen to the stream and I encountered an error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verification failed due to certificate expiration. After a brief examination using an SSL verifier, it appears that the certificate requires renewal.

**Comment by PaulRyu** [comment]
Yep, same here.

**Comment by aisstream** [comment]
Apologies, we thought we automated reloading the renewed cert in the load balancer.
