### ISSUE TITLE
Data in Oceania

### ISSUE THREAD

**Issue by neothone** [aisstream/issues#8]
Hello, It seems to me that I don't get data from Oceania... For example IMO 9387085 in Auckland actually. Howener, in your coverage area map, it seems to be covered. Can you help me ?

**Comment by aisstream** [comment]
Could you provide the bounding box you are not receiving data for ?

 There is a strong likelihood we are missing data for the area. Unfortunately our coverage in the area is a bit spotty and our coverage map does not take into account the true range of a AIS station only a fixed radius.

**Comment by neothone** [comment]
I have used bouding box [-180,-90],[180,90} in order to cover the entire world...

I have tried to split in 6 process with bouding box : 
- [-180,-90],[-125,90] 
- [-125,-90],[-22,90]
- [-22,-90],[50,90]
- [50,-90],[124,90]
- [124,-90],[180,90]

but I have the same result... data missing last days for example for IMO 9387085, whereas on https://www.vesselfinder.com/?imo=9387085 I see a signal yesterday.

With the split of process, it is very unstable... I have often the error "Client network socket disconnected before secure TLS connection was established".

Thank you for your help

**Comment by aisstream** [comment]
We will have a look at this today. What client/language are you using ?

 If you are splitting the clients over 6 processes it is very likely we are throttling the connection as we only allow one connection per ip address to be created a second. This would explain why the connection is dropped before TLS can be established. I just noticed this information is not included in our docs and will make an effort to ensure that it is added. 

If you want to connect with multiple bounding you can subscribe with one single client/process with the following subscription message. This should prevent you from being throttled. 
```
{
   "APIKey": <your api key>,
   "BoundingBoxes": [[[25.835302, -80.207729], [25.602700, -79.879297]], [[33.772292, -118.356139], [33.673490, -118.095731]] ]
}

``` 

 Unfortunately we do not have nearly the same coverage as vesselfinder.com which uses satellite and terrestrial AIS. That being said we will verify today if we receive data for the bounding boxes above

**Comment by aisstream** [comment]
We were able to verify that the bounding box `[[[-30.86, 180.0], [ -48.71, 157.0]]]`, which is a box around New Zealand ,is streaming data successfully. 

Looking at you bounding boxes it appears you are formatting `lang, lat` where we expect them to be in `lat, lang` which may explain partially the issue you are seeing. 

**However, for this portion of the world our coverage is very limited so it is still very likely we do not have coverage for the area you are interested in.**

**Comment by neothone** [comment]
Thank you very much for your answer and your work!

I close this issue and just suggest a cover area map more precise ;-)

**Comment by neothone** [comment]
Umm, I use node and your homepage mention `long, lat` and not `lat, long` : 
![image](https://user-images.githubusercontent.com/13251143/224645886-0f4a497c-1b93-4dd4-9878-9869f42fa54a.png)

**Comment by aisstream** [comment]
Thank you for identifying this. I had a feeling we had it incorrectly set somewhere but only checked the docs. I will open another issue to fix this and make it more obvious. 

Apologies for that.

**Comment by aisstream** [comment]
Opened https://github.com/aisstream/issues/issues/9 to track documentation changes.
