### ISSUE TITLE
API Key for one user working, API Key for another not

### ISSUE THREAD

**Issue by PaulRyu** [aisstream/issues#80]
Noted an interesting behavior today. A colleague was playing around with my AIS streamer and was running into this error:
![image](https://github.com/aisstream/issues/assets/31260254/bb1ab368-3187-4c5a-8863-173eaa3a798b)

To check out what was happening, I turned the streamer on with my API Key and it ran completely fine. It turns out that his API Key results in this error. 

Is this because he hit a usage limit with his API Key? or is the payload somehow returning differently for him? Thank you.

**Comment by aisstream** [comment]
Each account can only have so many active connections open at one time. Did the keys belong to the same Github account by any chance ?

**Comment by PaulRyu** [comment]
The keys belonged to different users; I haven't seen this issue come up again since then so will close the issue. Thank you.
